# This is the advanced version of the config.
# Compared to the basic version, this advanced version lets you:
# - define multiple currencies.
# To use this config, delete the original config.yml and rename this file to config.yml
# If you need even more control, see config-expert.yml.
config-type: advanced

# Player-related settings
player:
  # Define different currencies here.
  currencies:
    money: # This is the name of the currency. It can only contain English letters and hyphens.
      # The display format of the currency. {amount} is replaced with the amount.
      # You can use InfoAPI format here.
      display-format:
        en: "${amount}"
      default: 100
      max: 1000000
    coin: # This is the name of another currency.
      display-format:
        en: "{amount} coins"
      default: 10
      max: 1000
